'use server';

import { Resend } from 'resend';
import { renderToBuffer } from '@react-pdf/renderer';
import EstimateDocument from '@/components/pdf/EstimateDocument';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function sendEstimateEmail(
	userEmail: string,
	userName: string,
	totalAmount: number,
	projectType: string,
	aiSpecs: Record<string, string>, // <--- Added the fifth argument here
) {
	try {
		// 1. Generate the highly-detailed PDF buffer securely on the server
		const pdfBuffer = await renderToBuffer(
			<EstimateDocument
				consumerName={userName}
				projectType={projectType}
				date={new Date().toLocaleDateString()}
				aiSpecs={aiSpecs}
				estimatedValue={totalAmount}
			/>,
		);

		// 2. Send the HTML email WITH the attached PDF buffer
		const { data, error } = await resend.emails.send({
			from: 'BUILDRAIL Estimates <onboarding@resend.dev>', // Keep this as your testing domain for now
			to: [userEmail],
			subject: `Your Detailed Estimate: ${projectType}`,
			attachments: [
				{
					filename: `${projectType.replace(/\s+/g, '-')}-Estimate.pdf`,
					content: pdfBuffer,
				},
			],
			html: `
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-w: 600px; margin: 0 auto; color: #0f172a; padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px;">
          <div style="text-align: center; margin-bottom: 24px;">
            <h1 style="color: #0f172a; margin: 0; font-size: 24px;">Estimate Ready</h1>
            <p style="color: #64748b; margin-top: 4px; font-size: 14px;">${projectType} via Satellite Extraction</p>
          </div>
          
          <p style="font-size: 16px;">Hi ${userName},</p>
          <p style="font-size: 16px; line-height: 1.5;">Thank you for using our transparent estimation engine. Your turnkey project is estimated at <strong>$${totalAmount.toLocaleString()}</strong>.</p>
          
          <div style="background-color: #f8fafc; padding: 20px; border-left: 4px solid #2563eb; border-radius: 4px; margin: 24px 0;">
            <p style="margin: 0; font-size: 14px; color: #334155; line-height: 1.5;">
              <strong>Your Detailed Blueprint:</strong><br/>
              We have attached a highly detailed, itemized PDF ledger to this email breaking down your costs across Materials, Labor, and Logistics.
            </p>
          </div>
          
          <p style="font-size: 16px; line-height: 1.5;">When you are ready to verify these numbers and lock in your price with a site visit, simply reply to this email.</p>
          
          <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 30px 0;" />
          <p style="font-size: 12px; color: #94a3b8; text-align: center;">Securely generated by BUILDRAIL</p>
        </div>
      `,
		});

		if (error) {
			console.error('Resend API Error:', error);
			return { success: false, error: error.message };
		}

		return { success: true, data };
	} catch (error) {
		console.error('Server Action Error:', error);
		return { success: false, error: 'Server error sending email' };
	}
}
